name: fic12_fe
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  esc_pos_utils_plus: ^2.0.4
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  horizontal_data_table: ^4.3.1
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  open_file_plus: ^3.4.1+1
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  print_bluetooth_thermal: ^1.1.1
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  widgets_to_image: ^1.0.0
  mobile_scanner: ^6.0.1
  

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
